apiVersion: v1
kind: Service
metadata:
  name: configuration-service
spec:
  type: ClusterIP
  selector:
    app: configuration-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
